# Generated by Django 4.2.5 on 2023-09-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_image_article_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img',
            new_name='image',
        ),
    ]
