# Generated by Django 4.2.5 on 2023-09-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_img_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='img',
        ),
    ]
